"""Name machinery for the synthetic world (M1).

Manufactures the messiness that entity resolution exists to collapse: the
same fictional person written under different spellings, abbreviations and
scripts across sources. Everything here is deterministic — callers pass in
an explicit `random.Random`, never a global one — so the whole world can be
regenerated byte-for-byte from one seed (see docs/architecture.md §6.1).
"""

from __future__ import annotations

import calendar
import dataclasses
import datetime
import random

from faker import Faker
from indic_transliteration import sanscript
from indic_transliteration.sanscript import transliterate

# Never date.today() — the world must regenerate identically regardless of
# when it is run.
REFERENCE_YEAR = 2025
ADULT_AGE_RANGE = (18, 65)

# --- Data contracts --------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class TruePerson:
    person_id: str
    canonical_name: str
    dob: datetime.date
    home_town: str


@dataclasses.dataclass(frozen=True)
class NameVariant:
    surface: str
    script: str  # 'Latn' | 'Deva' | 'Taml' | 'Beng'
    kind: str  # 'exact'|'spelling'|'abbreviation'|'transliteration'|'formal_surname'|'initials'


# --- Curated name lists (fictional people; real Indian name components) ----

FIRST_NAMES = sorted(
    {
        # North / Hindi belt / Punjabi / Gujarati / Marathi
        "Aarav", "Vivaan", "Aditya", "Vihaan", "Arjun", "Sai", "Reyansh", "Ayaan",
        "Krishna", "Ishaan", "Rohan", "Karan", "Rahul", "Amit", "Sanjay", "Vikram",
        "Manoj", "Suresh", "Rajesh", "Anil", "Deepak", "Ravi", "Ajay", "Vijay",
        "Sandeep", "Naveen", "Mohit", "Nikhil", "Gaurav", "Tarun", "Raj",
        "Mohammad", "Mohammed", "Ahmed", "Imran", "Farhan", "Zoya", "Aisha",
        "Saanvi", "Ananya", "Diya", "Pari", "Anika", "Ira", "Myra", "Kavya",
        "Riya", "Isha", "Priya", "Neha", "Pooja", "Anjali", "Sneha", "Divya",
        "Shreya", "Kritika", "Meera", "Sunita", "Geeta", "Lata", "Kiran",
        "Rekha", "Nisha", "Simran", "Harleen", "Gurpreet",
        # South Indian
        "Karthik", "Arun", "Vijayan", "Ramesh", "Ganesh", "Siva", "Murugan",
        "Prakash", "Senthil", "Dinesh", "Bala", "Ravindra", "Naresh", "Krishnan",
        "Venkatesh", "Rangan", "Subramaniam", "Azhagiri",
        "Lakshmi", "Priyanka", "Kavitha", "Meenakshi", "Deepa", "Shanthi",
        "Revathi", "Anitha", "Swathi", "Nithya", "Vidya", "Kalyani", "Padma",
        # East Indian (Bengali / Odia / Assamese)
        "Debashish", "Sourav", "Abhijit", "Partha", "Subrata", "Ranajit",
        "Pradip", "Bikash", "Tapan", "Sabyasachi", "Anirban",
        "Sharmila", "Mahua", "Ritu", "Piyali", "Suchitra", "Debjani", "Moumita",
        "Ipsita",
    }
)

SURNAMES = sorted(
    {
        "Kumar", "Sharma", "Verma", "Gupta", "Singh", "Yadav", "Mishra",
        "Tiwari", "Pandey", "Chauhan", "Rathore", "Malhotra", "Khanna",
        "Kapoor", "Chopra", "Bhatia", "Arora", "Agarwal", "Jain", "Bansal",
        "Saxena", "Srivastava", "Dubey", "Joshi", "Rana", "Solanki", "Patel",
        "Shah", "Mehta", "Desai",
        "Nair", "Menon", "Pillai", "Iyer", "Iyengar", "Reddy", "Rao", "Naidu",
        "Subramanian", "Krishnan",
        "Chatterjee", "Banerjee", "Mukherjee", "Ganguly", "Bose", "Sen",
        "Das", "Dutta", "Roy", "Ghosh", "Chakraborty", "Bhattacharya",
        "Sarkar", "Chattopadhyay", "Bandyopadhyay", "Mukhopadhyay",
        "Gangopadhyay",
        "Ali", "Khan", "Ahmed", "Hussain", "Sheikh",
    }
)

# Fictional town names within the synthetic "Demo District" (prd §7).
TOWNS = [
    "Rampur Ganj", "Netaji Colony", "Bishnupada", "Suryagram",
    "Anand Vihar Extension", "Basanti Nagar", "Dharam Ganj", "Chandan Bazar",
    "Lakshmi Vihar", "Shakti Nagar East", "Kanak Chowk", "Ambika Nagar",
]

# --- Spelling / abbreviation / equivalence tables ---------------------------

SURNAME_WOBBLES = {
    "kumar": "Kumaar", "sharma": "Sharmaa", "verma": "Vermaa", "singh": "Singhh",
    "reddy": "Reddi", "rao": "Raoo", "nair": "Nayar", "shah": "Shaah",
    "patel": "Pattel", "gupta": "Guptaa", "mishra": "Mishraa", "yadav": "Yadhav",
    "tiwari": "Tiwaari", "pandey": "Pandeyy", "chauhan": "Chouhan",
    "joshi": "Joshee", "dubey": "Dubay", "saxena": "Saksena", "arora": "Aroraa",
    "kapoor": "Kapur", "khanna": "Khannaa", "malhotra": "Malhotraa",
    "bansal": "Bansaal", "jain": "Jaine", "agarwal": "Aggarwal",
    "srivastava": "Shrivastava", "rathore": "Rathor", "solanki": "Solankee",
    "desai": "Desaai", "mehta": "Mehata", "menon": "Menonn", "pillai": "Pillay",
    "iyer": "Aiyer", "naidu": "Naidoo", "banerjee": "Bannerjee",
    "mukherjee": "Mukerjee", "ganguly": "Gangooly", "bose": "Boss", "sen": "Sein",
    "das": "Dass", "dutta": "Dutt", "roy": "Roye", "ghosh": "Ghose",
    "chakraborty": "Chakravorty", "sarkar": "Sirkar", "khan": "Khaan",
    "ahmed": "Ahmad", "hussain": "Husain", "sheikh": "Shaikh", "ali": "Alli",
}

# Mohammad/Mohammed → Mohd/Md. (architecture.md §6.4 abbreviation table).
ABBREVIATIONS = {
    "mohammad": ["Mohd", "Md."],
    "mohammed": ["Mohd", "Md."],
}

# Formal-surname equivalence (Bengali), same pairs as resolve/indic_key.py.
FORMAL_SURNAME_MAP = {
    "chatterjee": "Chattopadhyay",
    "chattopadhyay": "Chatterjee",
    "banerjee": "Bandyopadhyay",
    "bandyopadhyay": "Banerjee",
    "mukherjee": "Mukhopadhyay",
    "mukhopadhyay": "Mukherjee",
    "ganguly": "Gangopadhyay",
    "gangopadhyay": "Ganguly",
}

_TRANSLITERATION_SCHEMES = {
    "Deva": sanscript.DEVANAGARI,
    "Taml": sanscript.TAMIL,
    "Beng": sanscript.BENGALI,
}

# Word-final virama/pulli left behind by naive ITRANS transliteration
# (Devanagari, Tamil, Bengali) — stripping it is a cosmetic floor, not a
# correctness fix; see transliterate_name()'s docstring.
_TRAILING_VIRAMAS = "्்্"


def transliterate_name(name: str, script: str) -> str:
    """Render a Latin name into the given Indic script.

    Naive ITRANS transliteration (used here only as a fallback for names with
    no curated script form — chiefly Faker filler names). It does not
    reproduce how a name is actually spelled in that script by a human: it
    drops long vowels at word ends and leaves a stray word-final virama. The
    virama is stripped below since it is the most visible artifact; the
    curated FIRST_NAME_SCRIPTS/SURNAME_SCRIPTS pairs are what actually fix
    the common-name case — see the Mohammad Ali trap, which uses a curated
    literal for the same reason.
    """
    scheme = _TRANSLITERATION_SCHEMES[script]
    raw = transliterate(name.lower(), sanscript.ITRANS, scheme)
    return " ".join(w.rstrip(_TRAILING_VIRAMAS) for w in raw.split())


# Curated Devanagari forms for every curated first name and surname (standard
# spellings). Devanagari is emitted for any name regardless of region, so
# every entry needs one. Left out: "Azhagiri" — genuinely uncertain what its
# standard Devanagari spelling is, so it stays on the transliteration
# fallback above rather than guessing.
FIRST_NAME_DEVA = {
    "Aarav": "आरव", "Vivaan": "विवान", "Aditya": "आदित्य", "Vihaan": "विहान",
    "Arjun": "अर्जुन", "Sai": "साई", "Reyansh": "रेयांश", "Ayaan": "अयान",
    "Krishna": "कृष्णा", "Ishaan": "ईशान", "Rohan": "रोहन", "Karan": "करण",
    "Rahul": "राहुल", "Amit": "अमित", "Sanjay": "संजय", "Vikram": "विक्रम",
    "Manoj": "मनोज", "Suresh": "सुरेश", "Rajesh": "राजेश", "Anil": "अनिल",
    "Deepak": "दीपक", "Ravi": "रवि", "Ajay": "अजय", "Vijay": "विजय",
    "Sandeep": "संदीप", "Naveen": "नवीन", "Mohit": "मोहित", "Nikhil": "निखिल",
    "Gaurav": "गौरव", "Tarun": "तरुण", "Raj": "राज",
    "Mohammad": "मोहम्मद", "Mohammed": "मोहम्मद", "Ahmed": "अहमद",
    "Imran": "इमरान", "Farhan": "फरहान", "Zoya": "ज़ोया", "Aisha": "आयशा",
    "Saanvi": "सांवी", "Ananya": "अनन्या", "Diya": "दिया", "Pari": "परी",
    "Anika": "अनिका", "Ira": "इरा", "Myra": "मायरा", "Kavya": "काव्या",
    "Riya": "रिया", "Isha": "ईशा", "Priya": "प्रिया", "Neha": "नेहा",
    "Pooja": "पूजा", "Anjali": "अंजलि", "Sneha": "स्नेहा", "Divya": "दिव्या",
    "Shreya": "श्रेया", "Kritika": "कृतिका", "Meera": "मीरा", "Sunita": "सुनीता",
    "Geeta": "गीता", "Lata": "लता", "Kiran": "किरण", "Rekha": "रेखा",
    "Nisha": "निशा", "Simran": "सिमरन", "Harleen": "हरलीन", "Gurpreet": "गुरप्रीत",
    "Karthik": "कार्तिक", "Arun": "अरुण", "Vijayan": "विजयन", "Ramesh": "रमेश",
    "Ganesh": "गणेश", "Siva": "शिव", "Murugan": "मुरुगन", "Prakash": "प्रकाश",
    "Senthil": "सेंथिल", "Dinesh": "दिनेश", "Bala": "बाला", "Ravindra": "रवींद्र",
    "Naresh": "नरेश", "Krishnan": "कृष्णन", "Venkatesh": "वेंकटेश",
    "Rangan": "रंगन", "Subramaniam": "सुब्रमण्यम",
    "Lakshmi": "लक्ष्मी", "Priyanka": "प्रियंका", "Kavitha": "कविता",
    "Meenakshi": "मीनाक्षी", "Deepa": "दीपा", "Shanthi": "शांति",
    "Revathi": "रेवती", "Anitha": "अनीता", "Swathi": "स्वाति", "Nithya": "नित्या",
    "Vidya": "विद्या", "Kalyani": "कल्याणी", "Padma": "पद्मा",
    "Debashish": "देवाशीष", "Sourav": "सौरव", "Abhijit": "अभिजीत",
    "Partha": "पार्थ", "Subrata": "सुब्रत", "Ranajit": "रणजीत",
    "Pradip": "प्रदीप", "Bikash": "बिकाश", "Tapan": "तपन",
    "Sabyasachi": "सब्यसाची", "Anirban": "अनिर्बाण", "Sharmila": "शर्मिला",
    "Mahua": "महुआ", "Ritu": "ऋतु", "Piyali": "पियाली", "Suchitra": "सुचित्रा",
    "Debjani": "देबजानी", "Moumita": "मौमिता", "Ipsita": "इप्सिता",
}

SURNAME_DEVA = {
    "Kumar": "कुमार", "Sharma": "शर्मा", "Verma": "वर्मा", "Gupta": "गुप्ता",
    "Singh": "सिंह", "Yadav": "यादव", "Mishra": "मिश्रा", "Tiwari": "तिवारी",
    "Pandey": "पांडे", "Chauhan": "चौहान", "Rathore": "राठौर",
    "Malhotra": "मल्होत्रा", "Khanna": "खन्ना", "Kapoor": "कपूर",
    "Chopra": "चोपड़ा", "Bhatia": "भाटिया", "Arora": "अरोड़ा",
    "Agarwal": "अग्रवाल", "Jain": "जैन", "Bansal": "बंसल", "Saxena": "सक्सेना",
    "Srivastava": "श्रीवास्तव", "Dubey": "दुबे", "Joshi": "जोशी", "Rana": "राणा",
    "Solanki": "सोलंकी", "Patel": "पटेल", "Shah": "शाह", "Mehta": "मेहता",
    "Desai": "देसाई", "Nair": "नायर", "Menon": "मेनन", "Pillai": "पिल्लई",
    "Iyer": "अय्यर", "Iyengar": "अयंगर", "Reddy": "रेड्डी", "Rao": "राव",
    "Naidu": "नायडू", "Subramanian": "सुब्रमण्यम", "Krishnan": "कृष्णन",
    "Chatterjee": "चटर्जी", "Banerjee": "बनर्जी", "Mukherjee": "मुखर्जी",
    "Ganguly": "गांगुली", "Bose": "बोस", "Sen": "सेन", "Das": "दास",
    "Dutta": "दत्ता", "Roy": "रॉय", "Ghosh": "घोष", "Chakraborty": "चक्रवर्ती",
    "Bhattacharya": "भट्टाचार्य", "Sarkar": "सरकार",
    "Chattopadhyay": "चट्टोपाध्याय", "Bandyopadhyay": "बंद्योपाध्याय",
    "Mukhopadhyay": "मुखोपाध्याय", "Gangopadhyay": "गंगोपाध्याय",
    "Ali": "अली", "Khan": "खान", "Ahmed": "अहमद", "Hussain": "हुसैन",
    "Sheikh": "शेख़",
}

# Tamil forms only for the South Indian subset of the curated lists — a
# Tamil rendering of e.g. "Khanna" has no natural spelling, so those stay on
# the transliteration fallback.
FIRST_NAME_TAML = {
    "Karthik": "கார்த்திக்", "Arun": "அருண்", "Vijayan": "விஜயன்",
    "Ramesh": "ரமேஷ்", "Ganesh": "கணேஷ்", "Siva": "சிவா", "Murugan": "முருகன்",
    "Prakash": "பிரகாஷ்", "Senthil": "செந்தில்", "Dinesh": "தினேஷ்",
    "Bala": "பாலா", "Ravindra": "ரவீந்திரா", "Naresh": "நரேஷ்",
    "Krishnan": "கிருஷ்ணன்", "Venkatesh": "வெங்கடேஷ்", "Rangan": "ரங்கன்",
    "Subramaniam": "சுப்ரமணியம்", "Lakshmi": "லக்ஷ்மி", "Priyanka": "பிரியங்கா",
    "Kavitha": "கவிதா", "Meenakshi": "மீனாக்ஷி", "Deepa": "தீபா",
    "Shanthi": "சாந்தி", "Revathi": "ரேவதி", "Anitha": "அனிதா",
    "Swathi": "ஸ்வாதி", "Nithya": "நித்யா", "Vidya": "வித்யா",
    "Kalyani": "கல்யாணி", "Padma": "பத்மா",
}

SURNAME_TAML = {
    "Nair": "நாயர்", "Menon": "மேனன்", "Pillai": "பிள்ளை", "Iyer": "ஐயர்",
    "Iyengar": "ஐயங்கார்", "Reddy": "ரெட்டி", "Rao": "ராவ்", "Naidu": "நாயுடு",
    "Subramanian": "சுப்ரமணியன்", "Krishnan": "கிருஷ்ணன்",
}

# Bengali forms only for the Bengali/East Indian subset.
FIRST_NAME_BENG = {
    "Debashish": "দেবাশীষ", "Sourav": "সৌরভ", "Abhijit": "অভিজিৎ",
    "Partha": "পার্থ", "Subrata": "সুব্রত", "Ranajit": "রণজিৎ",
    "Pradip": "প্রদীপ", "Bikash": "বিকাশ", "Tapan": "তপন",
    "Sabyasachi": "সব্যসাচী", "Anirban": "অনির্বাণ", "Sharmila": "শর্মিলা",
    "Mahua": "মহুয়া", "Ritu": "ঋতু", "Piyali": "পিয়ালি",
    "Suchitra": "সুচিত্রা", "Debjani": "দেবযানী", "Moumita": "মৌমিতা",
    "Ipsita": "ইপ্সিতা",
}

SURNAME_BENG = {
    "Chatterjee": "চ্যাটার্জী", "Banerjee": "ব্যানার্জী", "Mukherjee": "মুখার্জী",
    "Ganguly": "গাঙ্গুলী", "Bose": "বসু", "Sen": "সেন", "Das": "দাস",
    "Dutta": "দত্ত", "Roy": "রায়", "Ghosh": "ঘোষ",
    "Chakraborty": "চক্রবর্তী", "Bhattacharya": "ভট্টাচার্য", "Sarkar": "সরকার",
    "Chattopadhyay": "চট্টোপাধ্যায়", "Bandyopadhyay": "বন্দ্যোপাধ্যায়",
    "Mukhopadhyay": "মুখোপাধ্যায়", "Gangopadhyay": "গঙ্গোপাধ্যায়",
}

_FIRST_NAME_SCRIPTS = {"Deva": FIRST_NAME_DEVA, "Taml": FIRST_NAME_TAML, "Beng": FIRST_NAME_BENG}
_SURNAME_SCRIPTS = {"Deva": SURNAME_DEVA, "Taml": SURNAME_TAML, "Beng": SURNAME_BENG}


def _curated_script_form(canonical_name: str, script: str) -> str | None:
    """Compose a curated script rendering of a "First [Middle...] Last" name.

    Returns None (caller falls back to transliterate_name()) unless every
    token has a curated pair in that script.
    """
    tokens = canonical_name.split()
    first_map = _FIRST_NAME_SCRIPTS[script]
    last_map = _SURNAME_SCRIPTS[script]
    parts = []
    for i, tok in enumerate(tokens):
        pair = last_map.get(tok) if i == len(tokens) - 1 and len(tokens) > 1 else first_map.get(tok)
        if pair is None:
            return None
        parts.append(pair)
    return " ".join(parts)


# --- People generation -------------------------------------------------------


def _random_dob(rng: random.Random) -> datetime.date:
    age = rng.randint(*ADULT_AGE_RANGE)
    year = REFERENCE_YEAR - age
    month = rng.randint(1, 12)
    day = rng.randint(1, calendar.monthrange(year, month)[1])
    return datetime.date(year, month, day)


def make_people(n: int, rng: random.Random, *, start_id: int = 1) -> list[TruePerson]:
    """Deterministically generate `n` fictional people.

    Curated first-name/surname lists are the primary source; Faker (en_IN,
    hi_IN) fills in the remainder for volume.
    """
    fake = Faker(["en_IN", "hi_IN"])
    fake.seed_instance(rng.getrandbits(32))

    people = []
    for i in range(n):
        person_id = f"PERSON_{start_id + i:06d}"
        if rng.random() < 0.85:
            name = f"{rng.choice(FIRST_NAMES)} {rng.choice(SURNAMES)}"
        else:
            # hi_IN's own name() renders in Devanagari; canonical_name must
            # stay Latin script, so force the en_IN factory explicitly.
            name = fake["en_IN"].name()
        people.append(
            TruePerson(
                person_id=person_id,
                canonical_name=name,
                dob=_random_dob(rng),
                home_town=rng.choice(TOWNS),
            )
        )
    return people


# --- Variant generation -------------------------------------------------------


def _pick_translit_script(rng: random.Random) -> str:
    # prd §7: mostly Devanagari, a few Tamil/Bengali forms.
    return rng.choices(["Deva", "Taml", "Beng"], weights=[0.7, 0.15, 0.15], k=1)[0]


def variants_for(person: TruePerson, rng: random.Random, count: int) -> list[NameVariant]:
    """Produce `count` (2-5) plausible renderings of one person across sources."""
    n = max(2, min(5, count))
    tokens = person.canonical_name.split()
    first, rest = tokens[0], tokens[1:]
    surname = tokens[-1] if rest else ""

    exact = NameVariant(surface=person.canonical_name, script="Latn", kind="exact")

    others: list[NameVariant] = []

    wobble = SURNAME_WOBBLES.get(surname.lower())
    if wobble:
        others.append(
            NameVariant(surface=" ".join([first, *rest[:-1], wobble]), script="Latn", kind="spelling")
        )

    for ab in ABBREVIATIONS.get(first.lower(), []):
        others.append(NameVariant(surface=" ".join([ab, *rest]), script="Latn", kind="abbreviation"))

    others.append(
        NameVariant(surface=f"{first[0]}. {' '.join(rest)}".strip(), script="Latn", kind="initials")
    )

    formal = FORMAL_SURNAME_MAP.get(surname.lower())
    if formal:
        others.append(
            NameVariant(surface=" ".join([first, *rest[:-1], formal]), script="Latn", kind="formal_surname")
        )

    # Every non-Latin surface must be curated, therefore correct — no
    # transliterate_name() fallback here. If there's no curated pair for
    # this name in the chosen script, this person just gets no script
    # variant this round (the Latin candidates above still apply).
    script = _pick_translit_script(rng)
    surface = _curated_script_form(person.canonical_name, script)
    if surface is not None:
        others.append(NameVariant(surface=surface, script=script, kind="transliteration"))

    # De-duplicate by surface, preserving order (no set-based ordering).
    seen: list[str] = []
    deduped: list[NameVariant] = []
    for v in others:
        if v.surface not in seen:
            seen.append(v.surface)
            deduped.append(v)

    if len(deduped) > n - 1:
        idx = sorted(rng.sample(range(len(deduped)), n - 1))
        deduped = [deduped[i] for i in idx]

    return [exact, *deduped]


# --- The four identity traps (fixed fixtures, not randomly generated) -------


@dataclasses.dataclass(frozen=True)
class TrapSourceSurface:
    """A surface form paired with the source type the world generator must
    place it in — needed only for the Mohammad Ali trap (prd §4 beat 2)."""

    variant: NameVariant
    source_type: str


MOHAMMAD_ALI_TRAP = {
    "person": TruePerson(
        person_id="PERSON_900001",
        canonical_name="Mohammad Ali",
        dob=datetime.date(1988, 5, 12),
        home_town=TOWNS[0],
    ),
    "surfaces": [
        TrapSourceSurface(NameVariant("Mohammad Ali", "Latn", "exact"), "fir"),
        TrapSourceSurface(NameVariant("Mohd Ali", "Latn", "abbreviation"), "bank_kyc"),
        TrapSourceSurface(NameVariant("Md. Ali", "Latn", "abbreviation"), "phone_registration"),
        # Curated literal, NOT a transliterate_name() call — naive ITRANS
        # produces "मोहम्मद् अलि" (stray halant, short इ), not this.
        TrapSourceSurface(NameVariant("मोहम्मद अली", "Deva", "transliteration"), "company_register"),
    ],
}

RAJ_KUMAR_TRAP = {
    "persons": [
        TruePerson(
            person_id="PERSON_900002",
            canonical_name="Raj Kumar",
            dob=datetime.date(1979, 11, 2),
            home_town=TOWNS[1],
        ),
        TruePerson(
            person_id="PERSON_900003",
            canonical_name="Raj Kumar",
            dob=datetime.date(1993, 6, 30),
            home_town=TOWNS[2],
        ),
    ],
    "surfaces": [
        NameVariant("Raj Kumar", "Latn", "exact"),
        NameVariant("Rajkumar", "Latn", "spelling"),
        NameVariant("Raj Kumaar", "Latn", "spelling"),
        # Curated literal, not a transliterate_name() call.
        NameVariant("राज कुमार", "Deva", "transliteration"),
    ],
}

CHATTERJEE_TRAP = {
    "person": TruePerson(
        person_id="PERSON_900004",
        canonical_name="Debashish Chatterjee",
        dob=datetime.date(1982, 1, 15),
        home_town=TOWNS[3],
    ),
    "surfaces": [
        NameVariant("Debashish Chatterjee", "Latn", "exact"),
        NameVariant("Debashish Chaterjee", "Latn", "spelling"),
        NameVariant("Debashish Chattopadhyay", "Latn", "formal_surname"),
    ],
}

AZHAGIRI_TRAP = {
    "person": TruePerson(
        person_id="PERSON_900005",
        canonical_name="Karthik Azhagiri",
        dob=datetime.date(1990, 9, 9),
        home_town=TOWNS[4],
    ),
    "surfaces": [
        NameVariant("Karthik Azhagiri", "Latn", "exact"),
        NameVariant("Karthik Alagiri", "Latn", "spelling"),
    ],
}

IDENTITY_TRAPS = {
    "mohammad_ali": MOHAMMAD_ALI_TRAP,
    "raj_kumar": RAJ_KUMAR_TRAP,
    "chatterjee": CHATTERJEE_TRAP,
    "azhagiri": AZHAGIRI_TRAP,
}
